# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

 boot.initrd.luks.devices."old-home".device = "/dev/disk/by-uuid/5fc84ab3-bcfe-4ba3-ae48-c66cccd948f2";


  # boot.initrd.luks.devices."newssd" = {
  #   device = "/dev/disk/by-uuid/a32f7710-b4a6-4f9b-b03f-99ee92397185";
  #   keyFile = "/home/eckey.key";
  # };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BA9E-0400";
      fsType = "vfat";
    };
 fileSystems."/oldssd" =
   { device = "/dev/disk/by-uuid/3641fdef-f9b3-4fff-8376-dfd2c33be739";
     fsType = "ext4";
   };

#  boot.initrd.luks.devices."newssd".device = "/dev/disk/by-uuid/a32f7710-b4a6-4f9b-b03f-99ee92397185";

fileSystems."/" =
    { device = "/dev/disk/by-uuid/75af254f-8ca2-4c7e-8a3a-56184c782f91";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e4e79cb6-b2be-4298-8717-36c2ff29be74";
      fsType = "btrfs";
    };
  boot.initrd.luks.devices."actual-home".device = "/dev/disk/by-uuid/a32f7710-b4a6-4f9b-b03f-99ee92397185";


#  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
